/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.adesso;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WsApplicationTest {
    @Test void appHasAGreeting() {
        WsApplication classUnderTest = new WsApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
