/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.adesso;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WsApplication {
     public static void main(String[] args) {
         SpringApplication.run(WsApplication.class, args);
    }
}
